apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootstrap-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bootstrap-web
  template:
    metadata:
      labels:
        app: bootstrap-web
    spec:
      containers:
      - name: bootstrap-web
        image: bootstrap-web:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: bootstrap-web-service
spec:
  selector:
    app: bootstrap-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer